name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
  CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}

jobs:
  build-lint:
    env:
      DATABASE_URL: file:./db.sqlite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup
        uses: ./tooling/github/setup

      - name: Build, lint and type-check
        run: pnpm turbo build lint type-check

      - name: Check workspaces
        run: pnpm manypkg check
